module : cnn.feature_extraction.FeatureExtraction
model : cnn.TwoHeadInception3
data_root : /content/drive/MyDrive/Thesis
dataset : cholec80_feature_extract.Cholec80FeatureExtract
out_features : 7
input_height : 299
input_width : 299
batch_size : 1000
fps_sampling : 1
fps_sampling_test : 1
learning_rate : 0.0001
dataset_mode : img_multilabel
early_stopping_metric : val_acc_phase
pretrained : True
save_top_k : 1
max_epochs : 30
min_epochs : 20
num_tasks : 2
num_sanity_val_steps : 4
test_extract : True
#accelerator: ddp_spawn
num_workers : 10
gpus : 0 # all available -1